name: Questions
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
targets:
  Questions:
    type: application
    platform: iOS
    sources:
      - Questions
      - ../cpp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.questions
      SWIFT_OBJC_BRIDGING_HEADER: $(PROJECT_DIR)/Questions/Questions-Bridging-Header.h
      HEADER_SEARCH_PATHS: $(PROJECT_DIR)/../cpp
